version: '3.8'

services:
  postgres_db:
    image: postgres:13
    container_name: dune_postgres_db
    environment:
      POSTGRES_USER: ${DB_USER:-your_db_user} # Use environment variable from host or default
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your_db_password}
      POSTGRES_DB: ${DB_DATABASE:-dune_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # Optional: You can mount the init.sql script to be run automatically
      # - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-your_db_user} -d ${POSTGRES_DB:-dune_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: # Defines the named volume for data persistence
    driver: local